"""empty message

Revision ID: 45d31a0a8fc9
Revises: 56f6efaee1f1
Create Date: 2019-02-21 10:51:45.638704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d31a0a8fc9'
down_revision = '56f6efaee1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sala', schema=None) as batch_op:
        batch_op.alter_column('schedule',
               existing_type=sa.VARCHAR(length=250),
               nullable=False, server_default='default_schedule')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sala', schema=None) as batch_op:
        batch_op.alter_column('schedule',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
